### ISSUE TITLE
Bootstrap v4.0.0

### ISSUE THREAD

**Issue by ReneSaboia** [puikinsh/gentelella#605] opened 2017-11-02 09:48 UTC
Gentelella does not work on bootstrap v4.0?

**Comment by William-H-M** [comment] 2017-11-02 12:13
Hi, in short no.

> Once Bootstrap 4 goes out of beta, this issue can/should be re-opened. This is quite a huge project with a large user base. It wouldn't be wise to push beta code (what BS4 currently is) into production.

Duplicate of #268

**Closed** 2017-11-02 12:24 UTC
Labels: duplicate
