### ISSUE TITLE
Dropdowns don't work

### ISSUE THREAD

**Issue by ylecuyer** [puikinsh/gentelella#381] opened 2017-01-27 15:35 UTC
Go to [https://colorlib.com/polygon/gentelella/form_buttons.html](https://colorlib.com/polygon/gentelella/form_buttons.html)

The Button Dropdown example doesn't work

**Comment by krzysiekpiasecki** [comment] 2017-01-28 11:32
I'm able to reproduce at 1.4.

**Comment by AndreiCN** [comment] 2017-06-06 14:33
That issue was solved some time ago and since nobody had nothing to add on this we will just close it for now.

**Closed by AndreiCN** 2017-06-06 14:33 UTC
