### ISSUE TITLE
 Couldn't open browser (if you are using BrowserSync in a headless environment, you might want to set the open option to false)

### ISSUE THREAD

**Issue by amrutsawant** [puikinsh/gentelella#618] opened 2017-11-23 17:43 UTC
[15:28:44] Using gulpfile ~\Downloads\bootstrapProject\gulpfile.js
[15:28:44] Starting 'js'...
[15:28:44] Starting 'sass'...
[15:28:44] Starting 'fa'...
[15:28:44] Starting 'fonts'...
[15:28:44] Finished 'fa' after 108 ms
[15:28:44] Finished 'js' after 150 ms
[15:28:44] Finished 'fonts' after 156 ms
[15:28:44] Finished 'sass' after 435 ms
[15:28:44] Starting 'serve'...
[15:28:44] Finished 'serve' after 30 ms
[15:28:44] Starting 'default'...
[15:28:44] Finished 'default' after 37 μs
[Browsersync] Access URLs:

   Local: http://localhost:3000
External: http://192.168.1.101:3000
      UI: http://localhost:3001
UI External: http://192.168.1.101:3001

[Browsersync] Serving files from: ./src
[Browsersync] Couldn't open browser (if you are using BrowserSync in a headless environment, you might want to set the open option to false)

**Comment by William-H-M** [comment] 2017-11-23 18:46
Duplicate of #489 
Please don't open issues unnecessarily, you have already asked at the linked issue.

**Closed** 2017-11-23 19:24 UTC
Labels: duplicate

**Comment by rsujith** [comment] 2020-08-31 09:46
I didnt understand this ?
