### ISSUE TITLE
browser not opening in gulp...

### ISSUE THREAD

**Issue by amrutsawant** [puikinsh/gentelella#619] opened 2017-11-24 15:01 UTC
[20:29:39] Starting 'js'...
[20:29:39] Starting 'sass'...
[20:29:39] Starting 'fa'...
[20:29:39] Starting 'fonts'...
[20:29:39] Finished 'fa' after 106 ms
[20:29:39] Finished 'js' after 140 ms
[20:29:39] Finished 'fonts' after 150 ms
[20:29:40] Finished 'sass' after 422 ms
[20:29:40] Starting 'serve'...
[20:29:40] Finished 'serve' after 32 ms
[20:29:40] Starting 'default'...
[20:29:40] Finished 'default' after 51 μs
[Browsersync] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://192.168.1.101:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.101:3001
 --------------------------------------
[Browsersync] Serving files from: ./src

i set open : false;   after this nothing responding....

**Comment by William-H-M** [comment] 2017-11-24 15:39
I'm pretty, but pretty, pretty sure, that this been the second time you have oppened this same issue and has been answered to you twice in less of 24 hours!

Please avoid spamming issues, a solution was given to StackOverflow, for more information please search the web about the specific problem.

@AndreiCN 
Duplicate of #489

**Closed** 2017-11-24 15:59 UTC
Labels: duplicate

**Comment by amrutsawant** [comment] 2017-11-24 16:03
Sry but this is not a duplicate issue....I'm facing this issue...And
searched also on web...I tried stackoverflow....But I'm not getting proper
solution for this..So kindly I'm asking....Plz help me..

**Comment by amrutsawant** [comment] 2019-09-01 18:37
Hey,

I just signed the petition "CM Devendra Fadnavis, JICA Stop the cutting of
3500 trees in Aarey Forest" and wanted to see if you could help by adding
your name.

Our goal is to reach 300,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/8yLvtnkYMj

Thanks!
Amrut
