### ISSUE TITLE
Multi Level Menu -> Level 2 not working on responsive

### ISSUE THREAD

**Issue by dmc129** [puikinsh/gentelella#742] opened 2018-09-21 12:46 UTC
On hamburger menu I can't navigate to Multi Level Menu -> Level 2
When clicking on "Level 1    v" the menu closes (with no navigation working)

**Comment by William-H-M** [comment] 2018-09-21 13:17
Duplicate of #490 

Please at least look up at older issues, just a few issues back was the same, only 3 issues back....

**Closed** 2018-09-21 13:20 UTC
