### ISSUE TITLE
custom.css and custom.css.min are different

### ISSUE THREAD

**Issue by vvnc** [puikinsh/gentelella#682] opened 2018-04-16 16:52 UTC
Minified and non-minified versions of `custom.css` are slightly different, but they should be the same, I suppose. For example, `h2` font size in the minified version is `18px` (the same as it [should be](https://colorlib.com/polygon/gentelella/index.html)), but non-minified version `h2` is `30px` which is ugly.

custom.css.min:
![image](https://user-images.githubusercontent.com/27448586/38823428-0afbd134-41af-11e8-9107-7a4957e0edf9.png)

custom.css:
![image](https://user-images.githubusercontent.com/27448586/38823532-4cc4c8aa-41af-11e8-89fb-3ba5080f87a9.png)

I'm using the latest gentelella from npm (1.4.0)

**Comment by William-H-M** [comment] 2018-04-17 03:57
I'm sure this is a Duplicate of #563 I think that https://github.com/puikinsh/gentelella/commit/558cd90192274dbff1e3dee9eb0cefbf27491b17 fixed it.

Maybe is that npm doesn't have this change, because they are part of 1.5 next release? @AndreiCN

**Comment by vvnc** [comment] 2018-04-18 08:51
Oh, that's great they've already fixed it, I'm looking forward for the next release!

**Closed** 2018-04-20 11:38 UTC
Labels: duplicate
