### ISSUE TITLE
Upgrade gauge.js

### ISSUE THREAD

**Issue by theyosh** [puikinsh/gentelella#525] opened 2017-07-06 10:23 UTC
Hi,

gauge.js is creating updates after three years. There are some improvements in there.
Could you update your version with the latest? I noticed that there are some fixes in there which I could use.

https://bernii.github.io/gauge.js/

Kind regards
Joshua

**Comment by AndreiCN** [comment] 2017-07-06 10:38
Hello there,

Well once we update it to the latest version will automatically bring some issues and since we have some another priorities for the moment we will have to postpone this.

We would like to see this work, you can make a PR whenever you want with it.

Since this is not a bug we will close this for the moment but you can open another one when you need to, have a nice day !

**Closed by AndreiCN** 2017-07-06 10:38 UTC
Labels: enhancement
