### ISSUE TITLE
Release gentenella in npm to 1.4.0 version

### ISSUE THREAD

**Issue by v-rudkovskiy** [puikinsh/gentelella#586] opened 2017-10-06 13:55 UTC
Please can you release gentenella 1.4.0 version in npm

**Comment by cristianraiber** [comment] 2017-10-06 15:54
@v-rudkovskiy - We are working on that.

**Comment by William-H-M** [comment] 2017-10-06 18:49
@cristianraiber shouldn't this be a 
Duplicate of #524 ?

**Comment by cristianraiber** [comment] 2017-10-06 19:50
@William-H-M - yep, it is.

**Closed by cristianraiber** 2017-10-06 19:50 UTC
Labels: duplicate
