### ISSUE TITLE
Left Menu: sublevel 2 does not work when nav-sm is set

### ISSUE THREAD

**Issue by AronHopkins** [puikinsh/gentelella#739] opened 2018-09-12 08:58 UTC
Hello

I was looking into an issue where I could not successfully get the subLevel2 menu working on my implementation. It works as expected when the body class is nav-md.

I looked at the Demo site and this exhibits the same behaviour. Load Demo site, set the menu left hand side to small. Click on the MultiLevel menu, then Menu1 with the dropdown chevron. This accessing the demo is directly from chrome (latest, stable release), firefox (latest, stable release) directly on https://colorlib.com/polygon/gentelella/.

I will look into this to see if I can establish the root cause is, however this is not my not area of development.
<img width="302" alt="screenshot 2018-09-12 at 09 49 41" src="https://user-images.githubusercontent.com/482390/45413994-51d15380-b672-11e8-8688-dbd6f50a3189.png">

Regards

Aron

**Comment by William-H-M** [comment] 2018-09-12 12:15
Duplicate of #490

**Closed** 2018-09-17 12:47 UTC
Labels: duplicate
