### ISSUE TITLE
Next stable release

### ISSUE THREAD

**Issue by krzysiekpiasecki** [puikinsh/gentelella#153] opened 2016-05-18 13:04 UTC
Is there any project roadmap? When we should expect another stable release? There was an introduction of bower manager and a lot of changes was merged into a master branch.

**Comment by RinkAttendant6** [comment] 2016-05-18 14:24
Also are there any plans on publishing to npm? There was the introduction of `package.json`. If so I would suggest tagging stable releases so users can `npm install` a specific version as needed.

**Comment by christianesperar** [comment] 2016-05-18 16:40
New release will coming soon, I just need to resolve issue where package is too big. One solution can be is by removing the vendor folder and will just manually use bower install but still using npm then execute bower command is too tasky so maybe there is a better approach.

**Comment by krzysiekpiasecki** [comment] 2016-05-18 17:00
>> One solution can be is by removing the vendor folder and will just manually use bower install but still using npm then execute bower command is too tasky

IMHO vendors are always per-project. They should not be distributed among the contributors. After cloning is quite natural installing dependencies. So I'm surprised that they are placed in the repository.

**Comment by RinkAttendant6** [comment] 2016-05-18 18:58
Generally Bower dependencies `bower_components` should only be committed if you are building an application, not if you're building a library/package designed to be consumed by others.

Same goes for npm dependencies in `node_modules`, if they're available on npm.

Composer is a different story though.

**Comment by christianesperar** [comment] 2016-05-19 10:53
Package is now available on npm and 1.2.0 is already available!

I'm quite confuse @RinkAttendant6, I think this is vice versa? Bower and NPM dependencies should remove if you have an app where all developer is knowledgeable on the technologies that they use.

In our case, some is still not knowledgeable on npm or bower so possibilty of moving away in themes is very high if they fail to install the required steps for npm or bower. 

We add bower, npm  and other package manger (future?) so it can be friendly on the developer who know use this technologies. Also bower is also add to easily pull out new updates on our dependencies.

**Comment by krzysiekpiasecki** [comment] 2016-05-19 17:34
Can We close the ticket?

**Comment by RinkAttendant6** [comment] 2016-05-19 18:14
Yes I believe the issue is resolved. As for developer-friendliness with Bower and npm, to each their own I suppose.

For example, [FullCalendar](https://github.com/fullcalendar/fullcalendar) lists its dependencies (jQuery and moment) as npm and Bower dependencies, respectively, instead of bundling them with the library.

Regardless, thank you for publishing on npm.

**Closed** 2016-05-19 21:03 UTC
