### ISSUE TITLE
When sidebar menu collapsed, Multilevel menu can not show level two menu items

### ISSUE THREAD

**Issue by kaven125** [puikinsh/gentelella#622] opened 2017-12-01 03:35 UTC
Hi, 
  When sidebar menu collapsed, Multilevel menu can not show level two menu items.
This is how to set or is a problem.

Thanks.

**Comment by William-H-M** [comment] 2017-12-01 12:30
Duplicate of #490 will be fixed on next release if not wrong.

@AndreiCN is there any status about it? Thanks.

**Comment by AndreiCN** [comment] 2017-12-04 14:46
Yes @William-H-M , it's already fixed but not released just yet, @SumonT2 already provided a solution for it. Please check again until open a ticket for this issue again and again, thank you !

**Closed by AndreiCN** 2017-12-04 14:46 UTC
