### ISSUE TITLE
Sidebar-menu not base on href

### ISSUE THREAD

**Issue by PakCu** [puikinsh/gentelella#551] opened 2017-08-20 15:54 UTC
Hi. How to change collapse and active menu on sidebar-menu base on add class current-page and active instead base of url (pageName.html). Thanks

**Comment by AndreiCN** [comment] 2017-08-28 09:38
No quite sure what you want to achieve , can you please provide a screenshot or something ?

**Comment by PakCu** [comment] 2017-08-28 15:37
sry for my bad english. what i mean, currently the highlighted sidebar menu base on which page (page url) i open. in-case i'm using mvc framework.. its only index page and controlled by controller to open which template page. base on your js file (below), how to change it to fix my solutions. thanks

`	// check active menu
	$SIDEBAR_MENU.find('a[href="' + CURRENT_URL + '"]').parent('li').addClass('current-page');

	$SIDEBAR_MENU.find('a').filter(function () {
		return this.href == CURRENT_URL;
	}).parent('li').addClass('current-page').parents('ul').slideDown(function() {
		setContentHeight();
	}).parent().addClass('active');
`

**Comment by AndreiCN** [comment] 2017-09-29 10:21
Can you provide a screenshot or so ?

**Comment by William-H-M** [comment] 2017-09-29 12:16
@AndreiCN you can close this because of what he mean is the solution given on #363
Duplicate of #363

**Comment by PakCu** [comment] 2017-09-30 06:13
are you really want answer my question or help me or not?

**Closed** 2017-09-30 06:13 UTC
Labels: question
