### ISSUE TITLE
Fixed top_nav

### ISSUE THREAD

**Issue by w4r0** [puikinsh/gentelella#509] opened 2017-06-19 14:50 UTC
Is there any way to fix the top_nav the same way as the footer or sidebar?

I tried using .menu_fixed but nothing happened.
And I also tried using .navbar-fixed-top but it hid .page-title below the top_nav.

Thanks

**Comment by William-H-M** [comment] 2017-06-19 19:21
Hi, this is a duplicate of #508 continue the issue there, please avoid open the same issue twice, thanks.

@AndreiCN please close this as a duplicate.

**Closed** 2017-06-20 00:17 UTC
