### ISSUE TITLE
merge error

### ISSUE THREAD

**Issue by micrometeor** [puikinsh/gentelella#635] opened 2017-12-27 01:51 UTC
have not deal with conflict
<img width="767" alt="merge" src="https://user-images.githubusercontent.com/12859751/34368005-718021f0-eaeb-11e7-810d-a2a25ee41e36.png">

**Comment by William-H-M** [comment] 2017-12-27 12:19
Duplicate of #433

**Closed** 2018-01-08 11:41 UTC
Labels: duplicate
