### ISSUE TITLE
multilevel menu cannot be opened

### ISSUE THREAD

**Issue by jqlinux** [puikinsh/gentelella#629] opened 2017-12-11 02:48 UTC
The menu bar to merge, multilevel menu cannot be opened

**Comment by AndreiCN** [comment] 2017-12-11 07:53
Can you provide a screenshot ?

**Comment by tripguard** [comment] 2017-12-11 09:10
I can give screenshots...
Briefly ... when you press <a id="menu_toggle"> the menu is minimized to the mobile view, the "Multilevel Menu" tab does not expand the third level of the attachment, but simply disappears.


![normal view](https://user-images.githubusercontent.com/34274752/33823338-d3e9bbda-de6b-11e7-8f13-4db2b0fdee54.JPG)

On the second photo, when you click on the second levelOne, the third level is not opened and the panel is closed
![bug_view in mobile](https://user-images.githubusercontent.com/34274752/33823359-ee8f49c8-de6b-11e7-88ec-0d3b7324f019.JPG)

**Comment by William-H-M** [comment] 2017-12-11 12:18
Duplicate of #490 Just 7 issues ago... there was one ticket open...

**Comment by AndreiCN** [comment] 2017-12-11 12:20
You already have the solution in there, ticket closed.

**Closed by AndreiCN** 2017-12-11 12:20 UTC
Labels: duplicate

**Comment by tripguard** [comment] 2017-12-11 12:28
Too lazy to look for, here's the code


$SIDEBAR_MENU.find('a').on('click', function(ev) {
		var $li = $(this).parent();
		if ($li.is('.active')) {
			$li.removeClass('active active-sm');
			$('ul:first', $li).slideUp(function() {
				setContentHeight();
			});
		}
		else
		{
			// prevent closing menu if we are on child menu
			if (!$li.parent().is('.child_menu')) {
				$SIDEBAR_MENU.find('li').removeClass('active active-sm');
				$SIDEBAR_MENU.find('li ul').slideUp();
			}else
			{
				if ( $BODY.is( ".nav-sm" ) )
				{
					if (!$li.parent().is('.child_menu')) {
						$SIDEBAR_MENU.find('li').removeClass('active active-sm');
						$SIDEBAR_MENU.find('li ul').slideUp();
					}
				}
			}
			$li.addClass('active');

			$('ul:first', $li).slideDown(function() {
				
			});
		}
	});
