### ISSUE TITLE
Merge conflict on your demo

### ISSUE THREAD

**Issue by GingerTe** [puikinsh/gentelella#698] opened 2018-06-04 20:39 UTC
Hello
It's looks like you got merge conflict on your demo website
![image](https://user-images.githubusercontent.com/23435842/40940196-b7652792-684f-11e8-8e8b-7be6169c05ea.png)

[General form](https://colorlib.com/polygon/gentelella/form.html)

**Comment by William-H-M** [comment] 2018-06-04 22:25
Duplicate of #433 
Close this thx

**Closed** 2018-06-15 13:58 UTC
