### ISSUE TITLE
Invalid Text in form page

### ISSUE THREAD

**Issue by giansalex** [puikinsh/gentelella#679] opened 2018-04-12 01:48 UTC
![image](https://user-images.githubusercontent.com/14926587/38652005-b063cb3e-3dc9-11e8-9828-219495d5ccae.png)

**Comment by William-H-M** [comment] 2018-04-12 12:43
Duplicate of #433 

Close this, thanks

**Closed** 2018-04-12 14:08 UTC

**Comment by cbgrullon** [comment] 2019-04-09 17:37
Duplicate of #433
